name: vlm-in-robotics
channels:
  - defaults
  - conda-forge
  - compilers
  - cmake
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.24.4
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
    - -e ./simpler_env/ManiSkill2_real2sim
    - -e ./simpler_env
    - -e ./openvla
    - packaging
    - ninja
    - flash-attn==2.6.1 --no-build-isolation
