name: vlm-in-robotics
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.24.4
  - compilers
  - cmake
  - pytorch
  - torchvision
  - torchaudio
  - cuda
  - pytorch-cuda=12.4
  - pip
  - pip:
    - -e ./simpler_env/ManiSkill2_real2sim
    - -e ./simpler_env
    - tensorflow==2.15.0
    - -r simpler_env/requirements_full_install.txt
    - tensorflow[and-cuda]==2.15.1
    - -e ./openvla
    - packaging
    - ninja
    - flash-attn==2.6.1
