name: vlm-in-robotics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - compilers
  - cmake
  - ffmpeg
  - pip
  - pip:
    - numpy==1.24.4
    - -e ./simpler_env/ManiSkill2_real2sim
    - -e ./simpler_env
    - -r llserver/dev_requirements.txt