name: vlm-in-robotics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - compilers
  - cmake
  - jupyter
  - pip
  - pip:
    - numpy==1.24.4
    - opencv-python-headless
    - -e ./simpler_env/ManiSkill2_real2sim
    - -e ./simpler_env
