version: "3.9"

services:
  openvla:
    build:
      context: ./models/openvla
      dockerfile: Dockerfile
    image: openvla:latest
    container_name: openvla
    ports:
      - "8001:3000"
    restart: unless-stopped
    volumes:
      - ./models/openvla:/app
