services:
  # openvla:
  #   build:
  #     context: ./models/openvla
  #     dockerfile: Dockerfile
  #   image: openvla:latest
  #   container_name: openvla
  #   environment:
  #     - HF_HOME=/cache/huggingface
  #   ports:
  #     - "8001:8000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./models/openvla:/app
  #     - /cache/huggingface:/cache/huggingface
  #   deploy:                           # swarm/k8s hints, ignored by plain compose
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  # ecot:
  #   build:
  #     context: ./models/ecot
  #     dockerfile: Dockerfile
  #   image: ecot:latest
  #   container_name: ecot
  #   environment:
  #     - HF_HOME=/cache/huggingface
  #   ports:
  #     - "8002:8000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./models/ecot:/app
  #     - /cache/huggingface:/cache/huggingface
  #   deploy:                           # swarm/k8s hints, ignored by plain compose
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  cogact:
    build:
      context: ./models/cogact
      dockerfile: Dockerfile
    image: cogact:latest
    container_name: cogact
    environment:
      - HF_HOME=/cache/huggingface
    ports:
      - "8003:8000"
    restart: unless-stopped
    volumes:
      - ./models/cogact:/app
      - /cache/huggingface:/cache/huggingface
    deploy:                           # swarm/k8s hints, ignored by plain compose
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

#  spatialvla:
#    build:
#      context: ./models/spatialvla
#      dockerfile: Dockerfile
#    image: spatialvla:latest
#    container_name: spatialvla
#    environment:
#      - HF_HOME=/cache/huggingface
#    ports:
#      - "8004:8000"
#    restart: unless-stopped
#    volumes:
#      - ./models/cogact:/app
#      - /cache/huggingface:/cache/huggingface
#    deploy:                           # swarm/k8s hints, ignored by plain compose
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]
